/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.adopcionesmascota.GUI.Catalogo;

import com.mycompany.adopcionesmascota.GUI.FMain;
import com.mycompany.adopcionesmascota.entities.Mascota;
import javax.swing.ImageIcon;

/**
 *
 * @author angel
 */
public class PetCardPanel extends javax.swing.JPanel {
    private Mascota mascota;
    private FMain mainFrame;
    /**
     * Creates new form PetCardPanel
     */
    public PetCardPanel() {
        initComponents(); 
    }

    public PetCardPanel(Mascota mascota, FMain mainFrame) {
       initComponents();

        this.mascota = mascota;
        this.mainFrame = mainFrame;
        
            System.out.println("PetCardPanel ctor - mascota=" + mascota + " mainFrame=" + mainFrame);


        lbNombreMascota.setText(this.mascota.getNombre());
        btn_infoMascota.setText("Ver Detalles");

        if (mascota.getUrlImagen() != null) {
            try {
                ImageIcon icon = new ImageIcon(getClass().getResource(mascota.getUrlImagen()));
                lbImagenMascota.setIcon(icon);
                lbImagenMascota.setText("");
            } catch (Exception e) {
                lbImagenMascota.setText("Sin Foto");
            }
        } else {
            lbImagenMascota.setText("Sin Foto");
        }

        btn_infoMascota.addActionListener(e -> {
            mainFrame.mostrarDetalles(this.mascota);
    });
                }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImagenMascota = new javax.swing.JLabel();
        btn_infoMascota = new javax.swing.JButton();
        lbNombreMascota = new javax.swing.JLabel();

        lbImagenMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagenMascota.setText("image");

        btn_infoMascota.setText("VER DETALLES");
        btn_infoMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoMascotaActionPerformed(evt);
            }
        });

        lbNombreMascota.setText("nombreMascota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addComponent(lbImagenMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbNombreMascota)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_infoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(lbImagenMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbNombreMascota)
                .addGap(18, 18, 18)
                .addComponent(btn_infoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_infoMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoMascotaActionPerformed
        lbNombreMascota.setText(mascota.getNombre());
        
        btn_infoMascota.addActionListener(e -> {
            mainFrame.mostrarDetalles(mascota);
        });
    }//GEN-LAST:event_btn_infoMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_infoMascota;
    private javax.swing.JLabel lbImagenMascota;
    private javax.swing.JLabel lbNombreMascota;
    // End of variables declaration//GEN-END:variables
}
