/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.adopcionesmascota.GUI;

import com.mycompany.Control.ControlDiseño;
import com.mycompany.Control.ControlDiseño.ViewNames;
import com.mycompany.adopcionesmascota.entities.Mascota;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author angel
 */
public class FMain extends javax.swing.JFrame {

    private JPanel panelPrincipal;
    private CardLayout cardLayout;
    private ControlDiseño controlDiseño;

    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();

        cardLayout = new CardLayout();
        panelContenidoDinamico.setLayout(cardLayout);

        controlDiseño = new ControlDiseño(this, panelContenidoDinamico, cardLayout);

        registerAllPanels();

        controlDiseño.goToMainCatalog();
    }

    private void registerAllPanels() {
        controlDiseño.createAndRegisterPanel(ViewNames.CATALOGO, JPMenuMostrarEspecies.class);
        controlDiseño.createAndRegisterPanel(ViewNames.SOLICITUDES, JPSolicitudes.class);
        controlDiseño.createAndRegisterPanel(ViewNames.CONTACTO, JPContacto.class);

        controlDiseño.createAndRegisterPanel(ViewNames.INFO_MASCOTA, FInfoMascota.class);
        controlDiseño.createAndRegisterPanel(ViewNames.PASO_1_PERSONAL, JPInfoPersonal.class);
        controlDiseño.createAndRegisterPanel(ViewNames.PASO_2_VIVIENDA, JPInfoVivienda.class);
        controlDiseño.createAndRegisterPanel(ViewNames.PASO_3_RAZONES, JPInfoRazones.class);
        controlDiseño.createAndRegisterPanel(ViewNames.PASO_4_RESUMEN, JPInfoResumen.class);

        controlDiseño.createAndRegisterPanel(ViewNames.ERROR_CITA, msg_ErrorCitaPend.class);
        controlDiseño.createAndRegisterPanel(ViewNames.ERROR_SOLICITUD, msg_ErrorSolicitud.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_inicio = new javax.swing.JButton();
        btn_solicitudes = new javax.swing.JButton();
        btn_contacto = new javax.swing.JButton();
        panelContenidoDinamico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelCabecera.setBackground(new java.awt.Color(255, 255, 255));
        panelCabecera.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 110, 33));
        jLabel1.setText("LA VIDA ES BELLA");

        btn_inicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_inicio.setText("Inicio");
        btn_inicio.setBorder(null);
        btn_inicio.setBorderPainted(false);
        btn_inicio.setContentAreaFilled(false);
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        btn_solicitudes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_solicitudes.setText("Mis Solicitudes");
        btn_solicitudes.setBorder(null);
        btn_solicitudes.setBorderPainted(false);
        btn_solicitudes.setContentAreaFilled(false);
        btn_solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitudesActionPerformed(evt);
            }
        });

        btn_contacto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_contacto.setText("Contacto");
        btn_contacto.setBorder(null);
        btn_contacto.setBorderPainted(false);
        btn_contacto.setContentAreaFilled(false);
        btn_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(122, 122, 122)
                .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_solicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        panelContenidoDinamico.setBackground(new java.awt.Color(235, 229, 220));
        panelContenidoDinamico.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContenidoDinamicoLayout = new javax.swing.GroupLayout(panelContenidoDinamico);
        panelContenidoDinamico.setLayout(panelContenidoDinamicoLayout);
        panelContenidoDinamicoLayout.setHorizontalGroup(
            panelContenidoDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContenidoDinamicoLayout.setVerticalGroup(
            panelContenidoDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContenidoDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelContenidoDinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        controlDiseño.goToMainCatalog();
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitudesActionPerformed
        controlDiseño.goToSolicitudes();
    }//GEN-LAST:event_btn_solicitudesActionPerformed

    private void btn_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contactoActionPerformed
        controlDiseño.goToContacto();
    }//GEN-LAST:event_btn_contactoActionPerformed

    public void mostrarDetalles(Mascota mascota) {

        FInfoMascota panelDetalles = new FInfoMascota(mascota);

        String nombreVista = "detalles_" + mascota.getId();

        panelContenidoDinamico.add(panelDetalles, nombreVista);

        cardLayout.show(panelContenidoDinamico, nombreVista);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_contacto;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_solicitudes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelContenidoDinamico;
    // End of variables declaration//GEN-END:variables
}
